// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ArK79ItcwuJLtxejRNhzVH8jykITWmg',
    appId: '1:869819618459:web:0d28f94c1349d87d98a23e',
    messagingSenderId: '869819618459',
    projectId: 'flutter-authentication-3748e',
    authDomain: 'flutter-authentication-3748e.firebaseapp.com',
    storageBucket: 'flutter-authentication-3748e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB75IMOBXRi17Ht0Pfi6aOS4V7-yd9dR6w',
    appId: '1:869819618459:android:05811b6338e1e12798a23e',
    messagingSenderId: '869819618459',
    projectId: 'flutter-authentication-3748e',
    storageBucket: 'flutter-authentication-3748e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFjZ1KETfgsf10o9geEFAEWaFbHIfOqbs',
    appId: '1:869819618459:ios:12cf240526b2019198a23e',
    messagingSenderId: '869819618459',
    projectId: 'flutter-authentication-3748e',
    storageBucket: 'flutter-authentication-3748e.appspot.com',
    iosClientId: '869819618459-h7epj6a77a31c9kb8cbh32r0ek8ustsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFjZ1KETfgsf10o9geEFAEWaFbHIfOqbs',
    appId: '1:869819618459:ios:6fc144f222c5c44898a23e',
    messagingSenderId: '869819618459',
    projectId: 'flutter-authentication-3748e',
    storageBucket: 'flutter-authentication-3748e.appspot.com',
    iosClientId: '869819618459-4ari5n9t1cqbid6coef3f8tt93tfjkaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthentication.RunnerTests',
  );
}
